// Generated by tools/webunlock.py - do not edit by hand.
// One entry per box sold. Each is the game's key, locked with that
// box's code. No MAC, no code and no buyer detail is stored here.
window.IMP_UNITS = {
 "v": 1,
 "salt": "J4cQJe2d9XPtcWGs2Trmhw==",
 "rounds": 310000,
 "keys": [
  {
   "i": "ZI3Jnl7NqwBuCq1T",
   "c": "5VeYD7R3bLpaLVZkYPT5DuDrv3YFsN5efcd0u3KSXoD6Y7Iqmm9TLQ3/NNDJFrMx"
  }
 ]
};
